Repository BEpyeong/BEpyeong, pull requests merged in 2023-01, with the labels that each got.

#4 design: TabBar UI 추가 (#1)
  src/assets/icons/관심목록_off.png
  src/assets/icons/관심목록_on.png
  src/assets/icons/마이페이지_off.png
  src/assets/icons/마이페이지_on.png
  src/assets/icons/홈_off.png
  src/assets/icons/홈_on.png
  src/components/common/TabBar/TabBar.jsx
  src/styles/CommonIcons.jsx
Labels: design

#5 design: 카테고리 리스트 UI 추가 (#2)
  src/components/common/Category/CategoryList.jsx
Labels: design

#7 design: 감정키워드 버튼과 이를 사용하는 카드 퍼블리싱
  src/components/common/Buttons/EmotionButton.jsx
  src/components/common/EmotionKeywordCard/EmotionKeywordCard.jsx
  src/styles/CommonImages.jsx
Labels: design

#9 design: 크기별 버튼 UI 추가 (#6)
  src/components/common/Buttons/BasicButton.jsx
Labels: design

#10 design: 관심목록 버튼 & 별점 버튼 UI 구현
  package.json
  src/assets/icons/heart_off.png
  src/assets/icons/heart_on.png
  src/assets/images/crown.png
  src/assets/images/당황스러워요_off.png
  src/assets/images/당황스러워요_on.png
  src/assets/images/별로에요_off.png
  src/assets/images/별로에요_on.png
  src/assets/images/속상해요_off.png
  src/assets/images/속상해요_on.png
  src/assets/images/이상해요_off.png
  src/assets/images/이상해요_on.png
  src/assets/images/좋아요_off.png
  src/assets/images/좋아요_on.png
  src/assets/images/평범해요_off.png
  src/assets/images/평범해요_on.png
  src/components/common/Buttons/FavoriteButton.jsx
  src/components/common/Buttons/StarRateButton.jsx
Labels: design

#16 design: 알림함 글 목록 및 신고 접수 관리에 사용될 알림목록 UI 퍼블리싱 작업
  src/assets/icons/알림목록_신고.png
  src/assets/icons/알림목록_작성한글평가.png
  src/assets/icons/알림목록_평가한글마감.png
  src/components/common/NoticeList/NoticeList.jsx
  src/styles/CommonIcons.jsx
Labels: design

#15 chore: import시, 절대경로 사용을 위한 파일 추가 및 코드 수정
  jsconfig.json
  src/components/EmotionKeywordCard/EmotionKeywordCard.jsx
  src/components/common/Buttons/EmotionButton.jsx
  src/components/common/Buttons/FavoriteButton.jsx
  src/components/common/TabBar/TabBar.jsx
  src/styles/CommonIcons.jsx
  src/styles/CommonImages.jsx
Labels: intergration

#23 design: 게시글 체크박스 UI 퍼블리싱
  src/assets/icons/게시글_옵션추가_off.png
  src/assets/icons/게시글_옵션추가_on.png
  src/components/common/Buttons/PostCheckbox.jsx
  src/styles/CommonIcons.jsx
Labels: design

#19 design: 키워드 Tag 및 버튼 UI 퍼블리싱 작업
  src/components/common/Buttons/KeywordTagButton.jsx
Labels: design

#24 design: 각 상황별 레이아웃 및 input 창 UI 추가
  src/assets/icons/icon_검색.png
  src/assets/icons/icon_뒤로가기.png
  src/assets/icons/icon_알림.png
  src/assets/icons/icon_체크.png
  src/assets/icons/icon_햄버거.png
  src/components/common/AppBar/TabPageAppBar.jsx
  src/components/common/Buttons/BasicIconButton.jsx
  src/components/common/Input/Input.jsx
  src/components/layout/ContentsLayout/ContentsLayout.jsx
  src/components/layout/ContentsLayout/FrameLayout.jsx
  src/styles/CommonIcons.jsx
Labels: design, feat

#26 design: 프로필 이미지 업로드 UI 퍼블리싱
  src/assets/icons/프로필업로드.png
  src/assets/images/프로필_기본.png
  src/components/common/Buttons/ProfileImage.jsx
  src/components/common/ProfileImage/ProfileImage.jsx
Labels: design

#30 design: 게시글 캘린더 UI 퍼블리싱 작업
  src/assets/icons/게시글_달력.png
  src/components/common/Buttons/Date.jsx
  src/styles/CommonIcons.jsx
Labels: design

#32 design: 게시글 사진 추가/삭제 UI 구현
  src/assets/icons/게시글_사진삭제.png
  src/assets/icons/게시글_사진추가.png
  src/components/common/Buttons/PostImgAddButton.jsx
  src/components/common/Buttons/PostImgDeleteButton.jsx
  src/styles/CommonIcons.jsx
Labels: design

#29 design: 게시글인 카드형 피드 UI 구현
  src/components/common/Buttons/StarRateButton.jsx
  src/components/common/FeedList/FeedList.jsx
  src/styles/CommonIcons.jsx
Labels: design, asset

#38 design: 회원가입 페이지에 대한 전체적인 퍼플리싱
  src/components/common/Buttons/BasicButton.jsx
  src/pages/JoinMembershipPage/JoinMembershipPage.jsx
  src/styles/CommonIcons.jsx
  src/styles/CommonImages.jsx
Labels: design

#39 design: 글 작성하기 페이지 UI 퍼블리싱 작업
  src/components/common/Buttons/BasicButton.jsx
  src/pages/PostPage/PostUploadPage/PostUploadPage.jsx
Labels: design

#35 design: 로그인 페이지 퍼블리싱 작업
  src/assets/images/logo.png
  src/components/common/Buttons/BasicButton.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/styles/CommonImages.jsx
Labels: design

#42 refactor: 시멘틱한 회원가입 페이지를 위해 form 태그 추가 및 필요없는 input 태그 제거
  src/assets/icons/FeedIcon_best.png
  src/assets/icons/FeedIcon_date.png
  src/assets/icons/FeedIcon_thumb.png
  src/assets/icons/FeedIcon_voteDate.png
  src/pages/JoinMembershipPage/JoinMembershipPage.jsx
Labels: cleanup, refactor

#43 design: 알림 페이지 UI 퍼블리싱 작업
  src/components/common/AppBar/TabPageAppBar.jsx
  src/components/common/NoticeList/NoticeList.jsx
  src/pages/NoticePage/NoticePage.jsx
Labels: design

#48 design: 전체적인 검색페이지 퍼블리싱
  src/assets/icons/검색리스트_삭제_아이콘.png
  src/assets/icons/검색리스트_아이콘.png
  src/components/common/FeedList/Feed/Feed.jsx
  src/components/common/FeedList/FeedList.jsx
  src/pages/SearchPage/RecentSearch/RecentSearch.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/SearchedFeedList/SearchedFeedList.jsx
  src/styles/CommonIcons.jsx
Labels: design

#46 design: 마이페이지 UI 퍼블리싱 작업
  src/assets/icons/마이페이지_프로필수정.png
  src/assets/images/마이페이지_기본프로필.png
  src/pages/MyPage/MyPage.jsx
  src/styles/CommonIcons.jsx
  src/styles/CommonImages.jsx
Labels: design, asset

#49 design: 관리자페이지 UI 퍼블리싱 작업
  src/components/common/Category/CategoryList.jsx
  src/pages/AdminPage/AdminPage.jsx
Labels: design

#65 design: 관심목록 화면 퍼블리싱 및 공통 토스트팝업 UI 구현
  src/components/RatingToastPopup/RatingToastPopup.jsx
  src/components/common/BasicToastPopup/BasicToastPopup.jsx
  src/pages/FavoriteFeedsPage/FavoriteFeedsPage.jsx
Labels: design

#57 design: 신고 접수 관리 페이지 UI 퍼블리싱 작업
  src/components/common/NoticeList/NoticeList.jsx
  src/pages/ReportManagementPage/ReportManagementPage.jsx
Labels: design

#59 design: 404 페이지 UI 퍼블리싱 작업
  src/assets/images/NotFound404.png
  src/pages/NotFoundPage/NotFoundPage.jsx
  src/styles/CommonImages.jsx
Labels: design, asset

#62 design: 상세피드 페이지 퍼블리싱
  src/assets/icons/좋아요.png
  src/assets/icons/좋아요_on.png
  src/pages/DetailFeedPage/DetailFeedPage.jsx
  src/styles/CommonIcons.jsx
Labels: design

#63 design: 전체적인 모달 UI 퍼블리싱 작업
  src/components/common/Modal/AlertModal.jsx
  src/components/common/Modal/OptionCheckModal.jsx
Labels: design
